_extends: .github
repository:
  name: renovate-scaffolder
  description: opinionated scaffolder for enabling Renovate on a project
  homepage: 'https://npm.im/@form8ion/renovate-scaffolder'
  private: false
